# Generated by Django 4.0.4 on 2022-05-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='realese_date',
            new_name='release_date',
        ),
    ]
